config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'restaurants#index'

  resources :restaurants, only: [ :index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end

  # get 'reviews/:id', to: 'reviews#show'
  resources :reviews, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [ :show ]
  # same as self.before_action ( :set_restaurant, { :only => [ :show, :index... ] } )
  # before_action is method of ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  # i do not use form_for? no need of Restaurant.new in method new ?
  # when I don't use strong params with whitelist, no need of restaurant_params
  def create
    # Restaurant.create(
    #   name: params[:name],
    #   category: params[:category],
    #   address: params[:address],
    #   phone_number: params[:phone_number]
    # )

    # @restaurant = Restaurant.new(restaurant_params)
    # @restaurant.save

    # Restaurant.create(restaurant_params)
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address, :phone_number)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_restaurant, only: [:new, :create]

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
    @restaurant = Restaurant.find(@review.restaurant_id)
  end

  def new
    # why whithout @restaurant, it doesn't work?
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      # without new http request, so that the form does not loose user's input data
      render :new
    end

  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to 'Top', root_path %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Text link -->
    <%= link_to "Team", "/team.html", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Notification link-->
    <a href="" class="navbar-wagon-item navbar-wagon-link">
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    </a>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-button btn">Post stuff</a> -->
    <button data-toggle="modal" data-target="#sign-up" class="navbar-wagon-item navbar-wagon-button btn">Post stuff</button>

    <div class="modal fade" id="sign-up">
      <h2>modal!!</h2>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<h1>Restaurants list</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
      <%= restaurant.category %>
      <%= restaurant.address %>
      <%= restaurant.phone_number %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add new restaurant', new_restaurant_path, class: 'btn btn-primary' %>
<%= link_to 'See the all reviews', reviews_path, class: 'btn btn-success' %>

app/views/restaurants/new.html.erb
<h1>Add new restaurant</h1>

<!-- <form action="/restaurants" method="post">
  <%#= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="name">
  <input type="text" name="category" placeholder="category">
  <input type="text" name="address" placeholder="address">
  <input type="text" name="phone_number" placeholder="phone number">
  <input type="submit">
</form>
 -->

<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.text_field :category %>
  <%= f.text_field :address %>
  <%= f.text_field :phone_number %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<ul>
  <li>Category: <%= @restaurant.category %></li>
  <li>Address: <%= @restaurant.address %></li>
  <li>Tel: <%= @restaurant.phone_number %></li>
</ul>

<ul>

</ul>

<%= link_to 'Create the review of this restaurant', new_restaurant_review_path(@restaurant) %>

app/views/reviews/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to 'Top', root_path %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Text link -->
    <%= link_to "Team", "/team.html", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Notification link-->
    <a href="" class="navbar-wagon-item navbar-wagon-link">
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    </a>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-button btn">Post stuff</a> -->
    <button data-toggle="modal" data-target="#sign-up" class="navbar-wagon-item navbar-wagon-button btn">Post stuff</button>

    <div class="modal fade" id="sign-up">
      <h2>modal!!</h2>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<h1>Reviews list</h1>

<ul>
  <% @reviews.each do |review| %>
    <li>
      <%= review.restaurant.name %>
      <%= review.content %>
      <%= review.rating %>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>Add new review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/show.html.erb
<h1>Review of the <%= @restaurant.name %></h1>

<%= @review.rating %>
<%= @review.content %>